# Generated by Django 3.2.8 on 2021-10-26 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular problem', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Problem name', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
