# Generated by Django 3.2.8 on 2021-10-30 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular problem', primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('S', 'Successful'), ('T', 'Time Limit Exceeded'), ('W', 'Wrong Answer'), ('U', 'Unknown')], default='U', max_length=1)),
                ('submissionTime', models.TimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.testcase')),
            ],
        ),
    ]
