# Generated by Django 3.2.8 on 2021-10-30 20:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='case',
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular submission', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SubmissionResultTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.submission')),
            ],
        ),
    ]
