# Generated by Django 3.2.8 on 2021-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211030_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submissionTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
