# Generated by Django 3.2.8 on 2021-10-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_submission_submissiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='executionLimit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
