# Generated by Django 3.2.8 on 2021-11-14 15:53

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_testcase_executionlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(default=0, upload_to=website.models.location),
            preserve_default=False,
        ),
    ]
