# Generated by Django 3.2.8 on 2021-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_submission_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='executionLimit',
            new_name='execution_limit',
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(choices=[('S', 'Successful'), ('T', 'Time Limit Exceeded'), ('W', 'Wrong Answer'), ('U', 'Unknown'), ('F', 'Failed'), ('C', 'Compilation Error')], default='U', max_length=1),
        ),
    ]
