# Generated by Django 3.2.8 on 2021-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20211206_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[(1, 'CPP'), (2, 'Python')], default=1, max_length=1),
        ),
    ]
